### ISSUE TITLE
Requests generated incorrectly

### ISSUE THREAD

**Issue by stefkes** [flipboxstudio/lumen-generator#106]
When generating a request with `php artisan make:request MyRequest` you end up with a class that has
```

protected function authorize()
{
	return true;
}

protected function rules()
{
	return [
		//
	];
}
```

But this gives `Fatal error: Declaration of App\Http\Requests\MyRequest::authorize() must be compatible with Anik\Form\FormRequest::authorize(): bool`

The generated class should contain
```

protected function authorize(): bool
{
	return true;
}

protected function rules(): array
{
	return [
		//
	];
}
```

**Comment by jorgemudry** [comment]
@stefkes it should be fixed now. update your package version please. sorry for the inconvenience and thank you for the report 👍

**Comment by stefkes** [comment]
My pleasure, thanks for the fix and your response.
