### ISSUE TITLE
make:request is not using proper class.

### ISSUE THREAD

**Issue by saifur-rahman-hasan** [flipboxstudio/lumen-generator#113]
I was wondering after getting this issue. 
{
	"message": "Class \"Anik\\Form\\FormRequest\" not found",
        ....
}

Then I have found a issue in its related stub file. File location given below. 
File: https://github.com/flipboxstudio/lumen-generator/blob/develop/src/LumenGenerator/Console/stubs/request.stub

**Comment by jorgemudry** [comment]
@saifur-rahman-hasan you need to require this library in order to use Form Request: https://github.com/ssi-anik/form-request
