### ISSUE TITLE
Add support for illuminate 9.* packages

### ISSUE THREAD

**Issue by Kaishiyoku** [flipboxstudio/lumen-generator#114]

**Comment by segunmicheal27** [comment]
you can copy from here [Lumen-Generator](https://github.com/segunmicheal27/lumen-generator) until they release update

**Comment by MaheKarim** [comment]
Please add support for 9

**Comment by altusmedia** [comment]
Please add this.

**Comment by altusmedia** [comment]
please add! much needed

**Comment by puzzle9** [comment]
~https://github.com/YaangVu/lumen-generator~

~https://packagist.org/packages/yaangvu/lumen-generator~

**Comment by UrbanSwati** [comment]
> you can copy from here [Lumen-Generator](https://github.com/segunmicheal27/lumen-generator) until they release update

@segunmicheal27
Thanks for the link and changes you made, how do install your package directly, I have tried to edit the composer.json to point to your repo but when registering the service it can't find the flipbox namespace to the package

**Comment by jorgemudry** [comment]
Solved here https://github.com/flipboxstudio/lumen-generator/pull/118

**Comment by segunmicheal27** [comment]
I love the package thanks for the change from the community
