### ISSUE TITLE
Add Support for lumen 10

### ISSUE THREAD

**Issue by mashoodpv** [flipboxstudio/lumen-generator#122]
waiting to add support for lumen 10

Problem 1
    - flipbox/lumen-generator[8.2.0, ..., 8.2.2] require illuminate/support ^5.5|^6.0|^7.0|^8.0|^8.17 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^9.0|^10.1).
    - illuminate/filesystem[v5.5.0, ..., v5.5.44] require illuminate/support 5.5.* -> found illuminate/support[v5.5.0, ..., v5.5.44] but it conflicts with your root composer.json require (^9.0|^10.1).
    - illuminate/filesystem[v5.6.0, ..., v5.8.36] require php ^7.1.3 -> your php version (8.2.3) does not satisfy that requirement.
    - illuminate/filesystem[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.2.3) does not satisfy that requirement.
    - illuminate/filesystem[v6.20.0, ..., v6.20.44] require illuminate/support ^6.0 -> found illuminate/support[v6.0.0, ..., v6.20.44] but it conflicts with your root composer.json require (^9.0|^10.1).
    - illuminate/filesystem[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.2.3) does not satisfy that requirement.
    - illuminate/filesystem[v7.29.0, ..., v7.30.6] require illuminate/support ^7.0 -> found illuminate/support[v7.0.0, ..., v7.30.6] but it conflicts with your root composer.json require (^9.0|^10.1).
    - illuminate/filesystem[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.2.3) does not satisfy that requirement.
    - illuminate/filesystem[v8.12.0, ..., v8.83.27] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^9.0|^10.1).
    - Root composer.json requires laravel/lumen-framework ^10.0 -> satisfiable by laravel/lumen-framework[v10.0.0].
    - You can only install one version of a package, so only one of these can be installed: illuminate/filesystem[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4, v10.0.0, ..., v10.1.5].
    - flipbox/lumen-generator[9.0.0, ..., 9.1.0] require illuminate/filesystem ^5.5|^6.0|^7.0|^8.0|^8.17|^9.0 -> satisfiable by illuminate/filesystem[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4].
    - laravel/lumen-framework v10.0.0 requires illuminate/filesystem ^10.0 -> satisfiable by illuminate/filesystem[v10.0.0, ..., v10.1.5].
    - Root composer.json requires flipbox/lumen-generator ^8.2|^9.0|^10.0 -> satisfiable by flipbox/lumen-generator[8.2.0, 8.2.1, 8.2.2, 9.0.0, 9.0.1, 9.1.0].

**Comment by jorgemudry** [comment]
Fixed on this PR: https://github.com/flipboxstudio/lumen-generator/pull/121
