### ISSUE TITLE
Lumen (5.4.6) (Laravel Components 5.4.*)

### ISSUE THREAD

**Issue by zongmi** [flipboxstudio/lumen-generator#15]
Fatal error: vendor\flipbox\lumen-generator\src\LumenGenerator\Console\TestMakeCommand.php on line 5
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot use Illuminate\Console\GeneratorCommand as GeneratorCommand because the name is already in use

vendor\flipbox\lumen-generator\src\LumenGenerator\Console\TestMakeCommand.php
//use Illuminate\Console\GeneratorCommand;
use Illuminate\Console;

**Comment by zongmi** [comment]
原谅我的英语水平不过关==。

**Comment by krisanalfa** [comment]
English please, Sir.

**Comment by zongmi** [comment]
I'm sorry, sir. My English is not up to standard.
Lumen (5.4.6) (Laravel Components 5.4.*) will use this error when it is used

Fatal error: vendor\flipbox\lumen-generator\src\LumenGenerator\Console\TestMakeCommand.php on line 5
[Symfony\Component\Debug\Exception\FatalErrorException]
Cannot use Illuminate\Console\GeneratorCommand as GeneratorCommand because the name is already in use

I don't know if I'm the only one who has this problem. But I was modified in my code
Vendor\flipbox\lumen-generator\src\LumenGenerator\Console\TestMakeCommand.php
//use Illuminate\Console\GeneratorCommand;
Use Illuminate\Console;

**Comment by mstaack** [comment]
can confirm this issue!

**Comment by joelhy** [comment]
Fixed by PR #14 #16
