### ISSUE TITLE
Creating Cache for Config/Routes

### ISSUE THREAD

**Issue by mstaack** [flipboxstudio/lumen-generator#2]
Hey man,

was wondering if this package should also optimize the configs/envs..for  performance reasons..etc..dotenv should not be used in production thing ;)

what do you think?

cheers max

**Comment by krisanalfa** [comment]
Hi, @mstaack. I think optimizing config and routes is something agnostic, means the developer can have it's own approach to achieve that. For this reason, we cannot apply that features, you can try to compiles all your config and routes on your own way, not ours. Sorry for this inconvenience. Closing issue.
