### ISSUE TITLE
Make:Controller XYZ creates incomplete controller

### ISSUE THREAD

**Issue by S0PEX** [flipboxstudio/lumen-generator#21]
Hey,

I just installed this package and then run the command php artisan make: controller XyzController.
The issue is that this gives me an incomplete implementation of your controller sub. I am not sure what causes this, but I only get the controller struct without any methods inside, so the .plain one, although I am not using --plain
Running this on lumen 5.5

Regards Artur

**Comment by joelhy** [comment]
You need to use `--resource` option: `php artisan make:controller XyzController --resource`.
