### ISSUE TITLE
make:mail with option

### ISSUE THREAD

**Issue by federicogodan** [flipboxstudio/lumen-generator#26]
Hi, we are making emails using artisan make:mail:

`php artisan make:mail OrderShipped --markdown=emails.orders.shipped`

Using the option --markdown throw an error:

`The "--markdown" option does not exist`

Are options not supported by lumen-generator?

TY

Lumen: 5.5
PHP: 7.1.13
OS: Fedora 27

**Comment by joelhy** [comment]
The make:mail command does not support markdown option.

**Comment by federicogodan** [comment]
Hi, I take that command from [laravel documentation](https://laravel.com/docs/5.5/mail#markdown-mailables)

**Comment by simonhamp** [comment]
@federicogodan AFAIK, the only thing it does differently in Laravel is use the `$this->markdown()` in place of `$this->view()` and create the actual view for you, so it's not tricky to swap those out.

That being said, the point of this package is to generate all of that.

@joelhy As Lumen doesn't include the necessary resources and classes to generate mailables, we have to `composer require illuminate/mail` to make the generated mailables work and this includes everything needed to render Markdown mailables, so I think it should be possible to generate a markdown mailable from `lumen-generator`.

**Comment by joelhy** [comment]
Sorry I am a little bit busy now, I will look into it a few days later.

**Comment by simonhamp** [comment]
That's understandable. I took a look and it seemed pretty straightforward so I've already prepared a PR for you. Let me know if there are any issues.

**Comment by joelhy** [comment]
@simonhamp Thank you very much!
