### ISSUE TITLE
Any plans for make:seeder ?

### ISSUE THREAD

**Issue by aluferraz** [flipboxstudio/lumen-generator#3]
Hi,

Any plans for including make:seeder command ?

**Comment by krisanalfa** [comment]
Added [here](https://github.com/flipboxstudio/lumen-generator/commit/0f7eb06c43c860127c80c58eaa2983b5fa6e7a1a).

**Comment by 00madz** [comment]
Thanks for your great project. For the seeder command to show up though (5.3.4) I had to add `'SeederMake' => 'command.seeder.make',` to $devCommands, also had to change the register call to add the Composer parameter as follows:
```
protected function registerSeederMakeCommand()
    {
        $this->app->singleton('command.seeder.make', function ($app) {
            return new Console\SeederMakeCommand($app['files'], new Composer($app['files']));
        });
    }
```

**Comment by krisanalfa** [comment]
Could you send a PR, please? Because I'm busy right now.

**Comment by joelhy** [comment]
With latest flipboxstudio/lumen-generator v5.4, using local env, and APP_DEBUG enabled, no extras work needed to make `make:seeder` show up.
