### ISSUE TITLE
Call to undefined method Symfony\Component\Process\ProcessUtils::escapeArgument()

### ISSUE THREAD

**Issue by phiter** [flipboxstudio/lumen-generator#30]
I've upgraded my lumen installation to 5.6 and I'm getting this error:

> In ServeCommand.php line 40:
> 
>   Call to undefined method Symfony\Component\Process\ProcessUtils::escapeArgument()

I haven't tested the other commands, but apparently this function has been removed.

**Comment by toksdotdev** [comment]
Same issue.

**Comment by joelhy** [comment]
Fixed in pull request #31
