### ISSUE TITLE
Failed opening required 'server.php'

### ISSUE THREAD

**Issue by Synchro** [flipboxstudio/lumen-generator#32]
The fix for #30 broke my setup after the 5.6 upgrade - I don't have a `server.php`, but I do have a public folder, so [this part of the change](https://github.com/flipboxstudio/lumen-generator/pull/31/commits/b8724811d47434530c2f047de856c538f51c66b9#diff-6e69af57aa4d9f8609e31b14eaaeabf6L46) broke it. I've not found any docs on server.php - is it something I'm supposed to have? The 5.6 docs suggest that a public folder is normal, e.g. in https://lumen.laravel.com/docs/5.6#configuration

**Comment by nox-xou** [comment]
my temporary fix.
edit: LumenGenerator\Console\ServeCommand.php

    protected function serverCommand()
    {
        if(file_exists("base_path()/server.php")) {
            $command = '%s -S %s:%s %s/server.php';
        } else {
            $command = '%s -S %s:%s -t %s/public/';
        }

        return sprintf($command,
            ProcessUtils::escapeArgument((new PhpExecutableFinder)->find(false)),
            $this->host(),
            $this->port(),
            ProcessUtils::escapeArgument(base_path())
        );
    }

**Comment by joelhy** [comment]
Fixed in release [5.6.1](https://github.com/flipboxstudio/lumen-generator/releases/tag/5.6.1)
