### ISSUE TITLE
php artisan tinker

### ISSUE THREAD

**Issue by semsphy** [flipboxstudio/lumen-generator#37]
I got this warning message: `PHP Warning:  include(): Filename cannot be empty on line 55`

Thanks,

**Comment by aqidd** [comment]
can you be more specific @semsphy - when and how did you get the warning message?

**Comment by simplegadget512** [comment]
Same problem. It happens when I run `php artisan tinker`

![20180610_012642-_screenshot](https://user-images.githubusercontent.com/31604644/41205017-091713a0-6cb2-11e8-8dcd-5c21ee8c6526.png)

**Comment by joelhy** [comment]
Fixed. Please use [v5.6](https://github.com/flipboxstudio/lumen-generator/releases/tag/5.6.4)
