### ISSUE TITLE
Not compatible with Lumen 5.6

### ISSUE THREAD

**Issue by baorv** [flipboxstudio/lumen-generator#38]
![image](https://user-images.githubusercontent.com/9483946/40724415-388ec61a-644b-11e8-8d06-3b5fa5ae92f5.png)

**Comment by joelhy** [comment]
Fixed

**Comment by baorv** [comment]
Awesome, thank @joelhy !

**Comment by joelhy** [comment]
Please use latest version [v5.6.3]( https://github.com/flipboxstudio/lumen-generator/releases/tag/5.6.3). @roanvanbao
