### ISSUE TITLE
usage of null coalescing operator breaks PHP 5.6 support

### ISSUE THREAD

**Issue by thomaskglas** [flipboxstudio/lumen-generator#51]
First of all, I'm not sure if this package is supposed to support PHP 5.6. If it is, support for PHP 5.6 breaks because of the use of the null coalescing operator on this line:
https://github.com/flipboxstudio/lumen-generator/blob/41ec263a697e714d925252ddf305ab80e542ad21/src/LumenGenerator/Console/ControllerMakeCommand.php#L57

Was getting this error after running `composer update`
> PHP Parse error:  syntax error, unexpected '?' in /app/vendor/flipbox/lumen-generator/src/LumenGenerator/Console/ControllerMakeCommand.php on line 57

**Comment by joelhy** [comment]
Fixed.
Please use  v5.6.9

**Comment by thomaskglas** [comment]
Thanks @joelhy! 
I am having trouble installing 5.6.9, the latest version on packagist is still 5.6.8. Am I doing something wrong?

**Comment by joelhy** [comment]
@krisanalfa Please update packagist package.

**Comment by joelhy** [comment]
For now, please use develop branch by adding following code to your composer.json:

```json
    "repositories": [
        {
            "type": "git",
            "url": "git@github.com:flipboxstudio/lumen-generator.git"
        },
    ]
```

```js
    "require": {
        "flipbox/lumen-generator": "dev-develop",
        // .......   your other packages here
    },
```


Then run `composer install`
