### ISSUE TITLE
Failed to generate in Lumen 6.0.3

### ISSUE THREAD

**Issue by webidew** [flipboxstudio/lumen-generator#60]
Trying to generate few models and others but failed. And after few diggin, found out the problem was in line 92 GeneratorCommand.php whichwas still calling str_replace_first().

Suggested Fix: replace it with Str::replaceFirst(). That should do the trick.

**Comment by fauzipadlaw** [comment]
@webidew if you know the problem, you can send PR though

**Comment by webidew** [comment]
Still new to git/github basically. Will try to do it later. But that was only a quickfix... Might not be the best though....

**Comment by fauzipadlaw** [comment]
Nah, that is okay, just send PR would be there someone else correcting it

**Comment by zaherg** [comment]
@webidew you need to install `laravel/helpers` to use the helpers. 

In Laravel 6 they removed the helpers to a separate package.

**Comment by ffuentese** [comment]
Yep, I had the same issue. You might add laravel/helpers as a dependency for your package.

**Comment by webidew** [comment]
PR sent

**Comment by joelhy** [comment]
Merged. Please use v6.0.1
