### ISSUE TITLE
RouteListCommand.php implode wrong order

### ISSUE THREAD

**Issue by pieczarkazsolt** [flipboxstudio/lumen-generator#64]
Hi, 
I found a tiny bug in the code:
`#62 'verb' => implode($innerRoute->getMethods(), '|'),`
`#67 'middleware' => implode($innerRoute->getMiddleware(), '|'),`
and in php docs: implode ( string $glue , array $pieces ) : string (https://www.php.net/manual/en/function.implode.php)

**Comment by joelhy** [comment]
Won't fix.
According to https://www.php.net/manual/en/function.implode.php:
```
Note:

implode() can, for historical reasons, accept its parameters in either order. For consistency with explode(), however, it may be less confusing to use the documented order of arguments.
```

For example:

```bash
>>> implode(',', [1,2]);
=> "1,2"
>>> implode([1,2], ',');
=> "1,2"
```

**Comment by pieczarkazsolt** [comment]
ok guy. i accept the answer, but: https://www.php.net/manual/en/migration74.deprecated.php.
and the code isn't consistent, becaue in Console/GeneratorCommand.php use this order: implode(',', [1,2]);

**Comment by joelhy** [comment]
Got it. PHP 7.4 compatibility will be considered, and this will be fixed.
