### ISSUE TITLE
Undefined variable: strictTypes

### ISSUE THREAD

**Issue by Jari-B** [flipboxstudio/lumen-generator#79]
Hello, 

I am currently receiving `Undefined variable: strictTypes` in `OptimizeCommand.php line 105`. $strictTypes is not defined in the function. 

Any possible solution to this? 

Using Lumen 7  and php 7.4.1. APP_DEBUG=false

**Comment by joelhy** [comment]
Please use version v6.0.10

**Comment by Jari-B** [comment]
Thank you!
